# Generated by Django 3.2.4 on 2021-06-14 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autosaloon_api', '0002_users_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='dob',
        ),
    ]
