# Generated by Django 3.2.4 on 2021-06-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosaloon_api', '0003_remove_users_dob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AlterField(
            model_name='saloon',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='saloon',
            name='phonenumber',
            field=models.CharField(max_length=11),
        ),
    ]
